-- 0. Crear BDD
DROP DATABASE IF EXISTS Banco;
CREATE DATABASE Banco;
USE Banco;

-- 0. Crear Usuario:
CREATE USER IF NOT EXISTS 'rodrigo'@'%' IDENTIFIED BY 'TuPasswordSegura1!';
GRANT ALL PRIVILEGES ON Banco.* TO 'rodrigo'@'%';

-- 1. Crear tablas:

-- ESTADO
CREATE TABLE ESTADO (
    CODESTCTA INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(30) NOT NULL
);

-- ENTIDAD
CREATE TABLE ENTIDAD (
    COD_BCO INT AUTO_INCREMENT PRIMARY KEY,
    BANCO VARCHAR(30) NOT NULL
);

-- SUCURSAL
CREATE TABLE SUCURSAL (
    COD_SUC INT AUTO_INCREMENT PRIMARY KEY,
    SUCURSAL VARCHAR(30) NOT NULL
);

-- SITUACION
CREATE TABLE SITUACION (
    INDSITUAR INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(20) NOT NULL
);

-- PERSONA
CREATE TABLE PERSONA (
    RUT INT PRIMARY KEY,
    NOMBRES VARCHAR(30) NOT NULL,
    APE_PAT VARCHAR(20) NOT NULL,
    APE_MAT VARCHAR(20)
);

-- CUENTA
CREATE TABLE CUENTA (
    COD_BCO INT,
    COD_SUC INT,
    NUMCONTRATO VARCHAR(12),
    CODESTCTA INT,
    FECALTA DATE NOT NULL,
    FECBAJA DATE,
    RUT INT,
    PRIMARY KEY (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA)
);

-- TARJETA
CREATE TABLE TARJETA (
    ENTIDAD INT,
    SUCURSAL INT,
    NUMCONTRATO VARCHAR(12),
    PAN VARCHAR(16) PRIMARY KEY,
    INDSITUAR INT NOT NULL,
    FECCADU DATE NOT NULL,
    TIPPER VARCHAR(10) NOT NULL,
    RUT INT
);

-- 2. FOREIGN KEYS
ALTER TABLE CUENTA 
    ADD CONSTRAINT FK_CUENTA_ESTADO 
    FOREIGN KEY (CODESTCTA) REFERENCES ESTADO(CODESTCTA);

ALTER TABLE CUENTA 
    ADD CONSTRAINT FK_CUENTA_PERSONA 
    FOREIGN KEY (RUT) REFERENCES PERSONA(RUT);

ALTER TABLE TARJETA 
    ADD CONSTRAINT FK_TARJETA_SITUACION 
    FOREIGN KEY (INDSITUAR) REFERENCES SITUACION(INDSITUAR);

ALTER TABLE TARJETA 
    ADD CONSTRAINT FK_TARJETA_PERSONA 
    FOREIGN KEY (RUT) REFERENCES PERSONA(RUT);

-- 4. Insertar ESTADO
INSERT INTO ESTADO (DESCRIPCION) VALUES 
('ACTIVA'),
('NO ACTIVA'),
('MOROSIDAD LEVE'),
('ACELERACIÓN'),
('CASTIGADA');

-- 5. Insertar SITUACION
INSERT INTO SITUACION (DESCRIPCION) VALUES
('SOLICITADA'),
('IMPRESA'),
('EN PODER DEL CLIENTE'),
('ACUSE RECIBO CLIENTE'),
('OPERATIVA'),
('BLOQUEADA ROBO'),
('CADUCADA'),
('BLOQUEADA PERDIDA'),
('DESTRUIDA'),
('BLOQUEADA FRAUDE'),
('INUTILIZABLE');

-- 6. Insertar ENTIDAD
INSERT INTO ENTIDAD (BANCO) VALUES
('BANCOESTADO'),
('SCOTIABANK'),
('SANTANDER'),
('ITAU'),
('BANCO DE CHILE');

-- 7. Insertar SUCURSAL
INSERT INTO SUCURSAL (SUCURSAL) VALUES
('SANTIAGO CENTRO 1'),
('MACUL'),
('ÑUÑOA'),
('PUENTE ALTO'),
('RENCA');

-- 8. PERSONA
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES
(12345678, 'JUAN CARLOS', 'GONZALEZ', 'PEREZ'),
(23456789, 'MARIA ISABEL', 'LOPEZ', 'SILVA'),
(34567890, 'PEDRO ANTONIO', 'RODRIGUEZ', 'MARTINEZ'),
(45678901, 'ANA MARIA', 'FERNANDEZ', 'GARCIA'),
(56789012, 'CARLOS ALBERTO', 'RAMIREZ', 'CASTILLO');

-- 9. CUENTA
INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT)
VALUES
(1, 1, 'CTO20240001', 1, CURDATE(), NULL, 12345678),
(2, 2, 'CTO20240002', 1, CURDATE(), NULL, 23456789),
(3, 3, 'CTO20240003', 2, CURDATE(), NULL, 34567890);

-- 10. TARJETA
INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITUAR, FECCADU, TIPPER, RUT)
VALUES
(1, 1, 'CTO20240001', '4111111111111111', 5, '2026-12-31', 'TITULAR', 12345678),
(2, 2, 'CTO20240002', '5111111111111111', 5, '2027-06-30', 'TITULAR', 23456789),
(3, 3, 'CTO20240003', '6111111111111111', 1, '2028-03-15', 'ADICIONAL', 34567890);

COMMIT;
